[plugins.'io.containerd.cri.v1.runtime'.containerd.runtimes.markweave-reverse]
  runtime_type = "io.containerd.runc.v2"

[plugins.'io.containerd.cri.v1.runtime'.containerd.runtimes.markweave-reverse.options]
  BinaryName = "/var/lib/rancher/k3s/data/markweave/markweave-runc-wrapper"
  SystemdCgroup = true
